### ISSUE TITLE
The libraries do not load with the function localPDB()

### ISSUE THREAD

**Issue by marinaEM** [cran/VarfromPDB#1]
Error loading libraries from function localPDB(). I think the function is not updated with the Jenkins database.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the DESCRIPTION file. Thanks!

**Comment by marinaEM** [comment]
I know, I am using the R package, the function does not run properly because the Jenkins link that the function calls is wrong.. I don't know where to report this rather than here.

**Comment by Shicheng-Guo** [comment]
Author: Zongfu Cao <caozongfu@gmail.com>; Lei Wang <isan.wong@gmail.com>
Maintainer: Zongfu Cao <caozongfu@gmail.com>
